<a href="https://colab.research.google.com/github/Bavesh-08/movie-recomendation-system-using-cosinesimilarity/blob/main/movie_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MOVIE RECOMMENDATION SYSTEM

TYPES

     --> CONTENT BASED
     --> POPULARITY BASED
     --> COLLABORATIVE

In [ ]:
# importing the dependencies

import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# data collection

movies_data=pd.read_csv('/content/movies.csv')
movies_data.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."


In [ ]:
# getting the shape of the data

movies_data.shape

(4803, 4)

In [ ]:
# selecting the features form the data

selected_features=['title','cast','crew']
print(selected_features)

['title', 'cast', 'crew']


In [ ]:
# combining all the three features

combined_features=movies_data['title']+' '+movies_data['cast']+' '+movies_data['crew']
print(combined_features)

0       Avatar [{"cast_id": 242, "character": "Jake Su...
1       Pirates of the Caribbean: At World's End [{"ca...
2       Spectre [{"cast_id": 1, "character": "James Bo...
3       The Dark Knight Rises [{"cast_id": 2, "charact...
4       John Carter [{"cast_id": 5, "character": "John...
                              ...                        
4798    El Mariachi [{"cast_id": 1, "character": "El M...
4799    Newlyweds [{"cast_id": 1, "character": "Buzzy"...
4800    Signed, Sealed, Delivered [{"cast_id": 8, "cha...
4801    Shanghai Calling [{"cast_id": 3, "character": ...
4802    My Date with Drew [{"cast_id": 3, "character":...
Length: 4803, dtype: object


In [ ]:
# cheking is there any null values

combined_features.isnull().sum()

np.int64(0)

In [ ]:
# there is no null values so we can move forward

In [ ]:
# converting the text data into feature vector

vectorizer=TfidfVectorizer()
feature_vector=vectorizer.fit_transform(combined_features)
print(feature_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1348690 stored elements and shape (4803, 419819)>
  Coords	Values
  (0, 344917)	0.036225271528857884
  (0, 352754)	0.12498517242778193
  (0, 75116)	0.010707593681226596
  (0, 353495)	0.12498517242778193
  (0, 374590)	0.005480294440935887
  (0, 408148)	0.010707593681226596
  (0, 356468)	0.3537557431904906
  (0, 231412)	0.013109561925789041
  (0, 366890)	0.3537557431904906
  (0, 373445)	0.3537557431904906
  (0, 328351)	0.01056535021628467
  (0, 390290)	0.3537557431904906
  (0, 401358)	0.008670765712092087
  (0, 418007)	0.009225238133867926
  (0, 392733)	0.12498517242778193
  (0, 391065)	0.013109561925789041
  (0, 165021)	0.013109561925789041
  (0, 335469)	0.009600306517349801
  (0, 419597)	0.00681225561952011
  (0, 401231)	0.0094010206907526
  (0, 75372)	0.005384619302711011
  (0, 360433)	0.008047602660781637
  (0, 368516)	0.005788798473135738
  (0, 344809)	0.010435492106922344
  (0, 165042)	0.013109561925789041
  :	:
  (4802,

COSINE SIMILARITY BLOCK

In [ ]:
# getting the similarity using the cosine similarty

similarity=cosine_similarity(feature_vector)
print(similarity)

[[1.         0.64034376 0.79863136 ... 0.44052355 0.26319567 0.3593574 ]
 [0.64034376 1.         0.65504323 ... 0.41175343 0.25829407 0.34759496]
 [0.79863136 0.65504323 1.         ... 0.4571217  0.27357131 0.37008118]
 ...
 [0.44052355 0.41175343 0.4571217  ... 1.         0.17114766 0.24129704]
 [0.26319567 0.25829407 0.27357131 ... 0.17114766 1.         0.15801803]
 [0.3593574  0.34759496 0.37008118 ... 0.24129704 0.15801803 1.        ]]


In [ ]:
# getting the shape of the similart

print(similarity.shape)

(4803, 4803)


In [ ]:
# getting movie from the user

movie_name=input('enter the movie name: ')

enter the movie name: iron man


In [ ]:
# creating a list with all the movie name given in the dataset

list_of_all_titles=movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# finding the close match for the movie name

find_close_match=difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [ ]:
close_match=find_close_match[0]
print(close_match)

Iron Man


In [ ]:
# finding the index of tghe movie of the movie with the name

index_of_the_movie=movies_data[movies_data.title==close_match].index.values[0]
print(index_of_the_movie)

68


In [ ]:
# getting the list of similar movie

similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, np.float64(0.6100701894062077)), (1, np.float64(0.5795840427211546)), (2, np.float64(0.6129850694350125)), (3, np.float64(0.673198688046166)), (4, np.float64(0.5357252662762957)), (5, np.float64(0.7205269015999666)), (6, np.float64(0.4692384757588369)), (7, np.float64(0.61931863768809)), (8, np.float64(0.5938234877513731)), (9, np.float64(0.6963130263410388)), (10, np.float64(0.5099976247586265)), (11, np.float64(0.558957881957099)), (12, np.float64(0.5702861385674568)), (13, np.float64(0.6336512123401021)), (14, np.float64(0.5857347394311688)), (15, np.float64(0.530414568090216)), (16, np.float64(0.6729559703943059)), (17, np.float64(0.5848227171714606)), (18, np.float64(0.5253860833862305)), (19, np.float64(0.5745593727005944)), (20, np.float64(0.6217465699497958)), (21, np.float64(0.5635059990196927)), (22, np.float64(0.562588787748457)), (23, np.float64(0.5649044577564999)), (24, np.float64(0.5555424206988987)), (25, np.float64(0.6684583128775686)), (26, np.float64(0.626880828

In [ ]:
len(similarity_score)

4803

In [ ]:
# sorting the movies based on tghe similarity score

sorted_similar_movies=sorted(similarity_score,key=lambda x:x[1],reverse=True)
print(sorted_similar_movies)



[(68, np.float64(1.0000000000000009)), (5, np.float64(0.7205269015999666)), (980, np.float64(0.7167874927582368)), (281, np.float64(0.7139219743507341)), (65, np.float64(0.7107985779487461)), (9, np.float64(0.6963130263410388)), (2225, np.float64(0.6932640942111726)), (2105, np.float64(0.6914864695955341)), (287, np.float64(0.6912731010122815)), (1847, np.float64(0.6895296697587098)), (849, np.float64(0.6863645331334515)), (1356, np.float64(0.6853285315876801)), (361, np.float64(0.6849125397028025)), (1161, np.float64(0.6833289560983875)), (630, np.float64(0.6832737094201329)), (928, np.float64(0.678747673899363)), (693, np.float64(0.6752444958898632)), (798, np.float64(0.6741437845396625)), (1421, np.float64(0.6735826947396251)), (3, np.float64(0.673198688046166)), (16, np.float64(0.6729559703943059)), (3886, np.float64(0.6722007813850248)), (72, np.float64(0.6701690418429613)), (4200, np.float64(0.6699853977979904)), (25, np.float64(0.6684583128775686)), (1174, np.float64(0.668032098

In [ ]:
# printing the similar movie based on the index

print("movie suggested for you")

i=1
for movie in sorted_similar_movies:
  index=movie[0]
  titel_from_index=movies_data[movies_data.index==index].title.values[0]
  if(i<30):
    print(i,'.',titel_from_index)
    i+=1

movie suggested for you
1 . Iron Man
2 . Spider-Man 3
3 . The Life of David Gale
4 . American Gangster
5 . The Dark Knight
6 . Batman v Superman: Dawn of Justice
7 . Inherent Vice
8 . 12 Years a Slave
9 . Django Unchained
10 . GoodFellas
11 . Changeling
12 . The Hangover
13 . You Don't Mess with the Zohan
14 . The Social Network
15 . What Women Want
16 . Moneyball
17 . Gone Girl
18 . The Internship
19 . Hoffa
20 . The Dark Knight Rises
21 . The Avengers
22 . It's a Wonderful Life
23 . Suicide Squad
24 . You Can't Take It With You
25 . Titanic
26 . Ride Along 2
27 . Mr. Smith Goes to Washington
28 . Gandhi
29 . Not Another Teen Movie
